# Centroid Calculation for Library Access Analsyis
## Historic South Central Neighborhood
### Maya Deshpande

Import necessary libraries and read in census tract data from 2010.

In [2]:
import geopandas as gpd
import pandas as pd
tracts = gpd.read_file('census_tracts_2010.geojson')
tracts.head()

ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed

,OBJECTID,GEOID10,CT10,LABEL,Shape__Area,Shape__Length,geometry
0,1,06037911001,911001,9110.01,5.518756e+08,130967.821357,"POLYGON ((-117.66713 34.55801, -117.66713 34.5..."
1,2,06037980003,980003,9800.03,2.870875e+08,101384.949924,"POLYGON ((-117.88062 34.76362, -117.88252 34.7..."
2,3,06037930301,930301,9303.01,1.517472e+09,232176.490067,"POLYGON ((-117.65525 34.39723, -117.65519 34.3..."
3,4,06037573003,573003,5730.03,6.505064e+05,3324.521203,"POLYGON ((-118.19925 33.79713, -118.19925 33.7..."
4,5,06037297602,297602,2976.02,9.014198e+05,4520.897188,"POLYGON ((-118.28799 33.72259, -118.28799 33.7..."

Select the necessary columns and rename them.

In [3]:
tracts = tracts[['GEOID10','LABEL','geometry']]
tracts.rename(columns = {'GEOID10':'FIPS'}, inplace = True)
tracts.head()

          FIPS    LABEL                                           geometry
0  06037911001  9110.01  POLYGON ((-117.66713 34.55801, -117.66713 34.5...
1  06037980003  9800.03  POLYGON ((-117.88062 34.76362, -117.88252 34.7...
2  06037930301  9303.01  POLYGON ((-117.65525 34.39723, -117.65519 34.3...
3  06037573003  5730.03  POLYGON ((-118.19925 33.79713, -118.19925 33.7...
4  06037297602  2976.02  POLYGON ((-118.28799 33.72259, -118.28799 33.7...

Manually identify a neighborhood's corresponding census tracts:
- Census Tract 2240.20, Los Angeles, CA
- Census Tract 2246, Los Angeles, CA
- Census Tract 2311, Los Angeles, CA
- Census Tract 2284.10, Los Angeles, CA
- Census Tract 2267.01, Los Angeles, CA
- Census Tract 2267.02, Los Angeles, CA
- Census Tract 2264.10, Los Angeles, CA
- Census Tract 2264.20, Los Angeles, CA
- Census Tract 2260.01, Los Angeles, CA
- Census Tract 2270.10, Los Angeles, CA
- Census Tract 2270.20, Los Angeles, CA
- Census Tract 2282.10, Los Angeles, CA
- Census Tract 2283.10, Los Angeles, CA
- Census Tract 2318, Los Angeles, CA
- Census Tract 2284.20, Los Angeles, CA
- Census Tract 2283.20, Los Angeles, CA
- Census Tract 2319.02, Los Angeles, CA
- Census Tract 2319.01, Los Angeles, CA
- Census Tract 2293, Los Angeles, CA
- Census Tract 2285, Los Angeles, CA
- Census Tract 2286, Los Angeles, CA
- Census Tract 2292, Los Angeles, CA

Create a new dataframe for census tracts in Historic South Central Los Angeles. Ignore warnings!

In [5]:
south_central = pd.DataFrame()
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2240.20'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2246'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2311'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2284.10'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2267.01'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2267.02'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2264.10'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2264.20'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2260.01'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2270.10'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2270.20'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2282.10'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2283.10'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2318'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2284.20'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2282.10'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2319.02'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2319.01'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2293'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2285'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2286'])
south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2292'])

south_central

/tmp/ipykernel_204/1133841884.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2240.20'])
/tmp/ipykernel_204/1133841884.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2246'])
/tmp/ipykernel_204/1133841884.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2311'])
/tmp/ipykernel_204/1133841884.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2284.10'])
/tmp/ipykernel_204/1133841884.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2267.01'])
/tmp/ipykernel_204/1133841884.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2267.02'])
/tmp/ipykernel_204/1133841884.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2264.10'])
/tmp/ipykernel_204/1133841884.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2264.20'])
/tmp/ipykernel_204/1133841884.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2260.01'])
/tmp/ipykernel_204/1133841884.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2270.10'])
/tmp/ipykernel_204/1133841884.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2270.20'])
/tmp/ipykernel_204/1133841884.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2282.10'])
/tmp/ipykernel_204/1133841884.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2283.10'])
/tmp/ipykernel_204/1133841884.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2318'])
/tmp/ipykernel_204/1133841884.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2284.20'])
/tmp/ipykernel_204/1133841884.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2282.10'])
/tmp/ipykernel_204/1133841884.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2319.02'])
/tmp/ipykernel_204/1133841884.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2319.01'])
/tmp/ipykernel_204/1133841884.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2293'])
/tmp/ipykernel_204/1133841884.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2285'])
/tmp/ipykernel_204/1133841884.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2286'])
/tmp/ipykernel_204/1133841884.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central = south_central.append(tracts.loc[tracts['LABEL'] == '2292'])

             FIPS    LABEL                                           geometry
734   06037224020  2240.20  POLYGON ((-118.26001 34.03113, -118.26009 34.0...
998   06037228410  2284.10  POLYGON ((-118.26526 34.01538, -118.26582 34.0...
763   06037226410  2264.10  POLYGON ((-118.25862 34.02581, -118.25876 34.0...
764   06037226420  2264.20  POLYGON ((-118.25200 34.02288, -118.25242 34.0...
1127  06037226001  2260.01  POLYGON ((-118.23926 34.02457, -118.23926 34.0...
766   06037227010  2270.10  POLYGON ((-118.23967 34.01801, -118.23968 34.0...
991   06037227020  2270.20  POLYGON ((-118.24675 34.01572, -118.24714 34.0...
994   06037228210  2282.10  POLYGON ((-118.24869 34.01241, -118.24890 34.0...
993   06037228310  2283.10  POLYGON ((-118.25652 34.01278, -118.25652 34.0...
996   06037228420  2284.20  POLYGON ((-118.26922 34.00918, -118.26964 34.0...
994   06037228210  2282.10  POLYGON ((-118.24869 34.01241, -118.24890 34.0...

Create a new dataframe containing centroid points for all polygons (tracts) in the South Central

In [7]:
south_central_centroids = pd.DataFrame()
south_central_centroids["lon"] = south_central["geometry"].centroid.x
south_central_centroids["lat"] = south_central["geometry"].centroid.y
south_central_centroids

/tmp/ipykernel_204/2675157724.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  south_central_centroids["lon"] = south_central["geometry"].centroid.x
/tmp/ipykernel_204/2675157724.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  south_central_centroids["lat"] = south_central["geometry"].centroid.y

             lon        lat
734  -118.268669  34.030488
998  -118.269125  34.013745
763  -118.262294  34.024204
764  -118.257074  34.021847
1127 -118.250287  34.024488
766  -118.247009  34.018530
991  -118.251945  34.015759
994  -118.253494  34.010417
993  -118.262428  34.011356
996  -118.271904  34.008265
994  -118.253494  34.010417

Read in library location data. Select relevant columns.

In [8]:
libraries = pd.read_csv('Libraries - City_County.csv')
desired_columns = ['org_name','Name','city', 'zip', 'latitude', 'longitude']
libraries_trimmed = libraries[desired_columns].copy()
pd.set_option('display.max_rows', None)
libraries.head()

,X,Y,OBJECTID,org_name,Name,addrln1,city,state,post_id,zip,latitude,longitude,POINT_X,POINT_Y
0,-118.272075,33.916229,63131,LA County,LA County Library - A C Bilbrew Library,150 E El Segundo Blvd,Los Angeles,CA,70540,90061,33.916229,-118.272075,6479121.690,1792005.891
1,-118.775331,34.143205,12484,LA County,LA County Library - Agoura Hills Library,29901 Ladyface Ct,Agoura Hills,CA,13303,91301,34.143205,-118.775331,6327070.691,1875400.200
2,-118.078456,33.887956,62972,LA County,LA County Library - Alondra Library,11949 Alondra Blvd,Norwalk,CA,70485,90650,33.887956,-118.078456,6537858.557,1781614.314
3,-118.133336,33.848716,62975,LA County,LA County Library - Angelo M. Iacoboni Library,4990 Clark Ave,Lakewood,CA,70486,90712,33.848716,-118.133336,6521183.090,1767351.676
4,-118.139522,34.698131,62979,LA County,LA County Library - Antelope Valley Bookmobile,601 W Lancaster Blvd,Lancaster,CA,70487,93534,34.698131,-118.139522,6519733.775,2076474.233

Create a dataframe containing all county libraries.

In [9]:
countylib = libraries_trimmed.loc[libraries_trimmed['org_name'] == 'LA County']

geocountylib = gpd.GeoDataFrame(countylib, 
                       crs='epsg:4326',
                       geometry=gpd.points_from_xy(countylib.longitude, countylib.latitude))
geocountylib.head()

,org_name,Name,city,zip,latitude,longitude,geometry
0,LA County,LA County Library - A C Bilbrew Library,Los Angeles,90061,33.916229,-118.272075,POINT (-118.27207 33.91623)
1,LA County,LA County Library - Agoura Hills Library,Agoura Hills,91301,34.143205,-118.775331,POINT (-118.77533 34.14321)
2,LA County,LA County Library - Alondra Library,Norwalk,90650,33.887956,-118.078456,POINT (-118.07846 33.88796)
3,LA County,LA County Library - Angelo M. Iacoboni Library,Lakewood,90712,33.848716,-118.133336,POINT (-118.13334 33.84872)
4,LA County,LA County Library - Antelope Valley Bookmobile,Lancaster,93534,34.698131,-118.139522,POINT (-118.13952 34.69813)

Create a dataframe containing all city libraries.

In [10]:
lapl = libraries_trimmed.loc[libraries_trimmed['org_name'] == 'City of LA']
geolapl = gpd.GeoDataFrame(lapl, 
                       crs='epsg:4326',
                       geometry=gpd.points_from_xy(lapl.longitude, lapl.latitude))
geolapl.head()

,org_name,Name,city,zip,latitude,longitude,geometry
87,City of LA,Los Angeles Public Library - Van Nuys Branch,Los Angeles,91401,34.183775,-118.446379,POINT (-118.44638 34.18377)
88,City of LA,Los Angeles Public Library - Alma Reaves Woods...,Los Angeles,90002,33.943847,-118.246428,POINT (-118.24643 33.94385)
89,City of LA,Los Angeles Public Library - Mark Twain Branch,Los Angeles,90003,33.948675,-118.282863,POINT (-118.28286 33.94868)
90,City of LA,Los Angeles Public Library - San Pedro Regiona...,Los Angeles,90731,33.735490,-118.292486,POINT (-118.29249 33.73549)
91,City of LA,Los Angeles Public Library - Robertson Branch,Los Angeles,90035,34.048354,-118.385804,POINT (-118.38580 34.04835)

Concatenate the city and county libraru dataframes.

In [11]:
geolibs = pd.concat([geolapl, geocountylib])
geolibs.head()

,org_name,Name,city,zip,latitude,longitude,geometry
87,City of LA,Los Angeles Public Library - Van Nuys Branch,Los Angeles,91401,34.183775,-118.446379,POINT (-118.44638 34.18377)
88,City of LA,Los Angeles Public Library - Alma Reaves Woods...,Los Angeles,90002,33.943847,-118.246428,POINT (-118.24643 33.94385)
89,City of LA,Los Angeles Public Library - Mark Twain Branch,Los Angeles,90003,33.948675,-118.282863,POINT (-118.28286 33.94868)
90,City of LA,Los Angeles Public Library - San Pedro Regiona...,Los Angeles,90731,33.735490,-118.292486,POINT (-118.29249 33.73549)
91,City of LA,Los Angeles Public Library - Robertson Branch,Los Angeles,90035,34.048354,-118.385804,POINT (-118.38580 34.04835)

In [12]:
geolibs.tail()

,org_name,Name,city,zip,latitude,longitude,geometry
82,LA County,LA County Library - West Hollywood Library,West Hollywood,90069,34.081673,-118.383376,POINT (-118.38338 34.08167)
83,LA County,LA County Library - Westlake Village Library,Westlake Village,91361,34.144475,-118.799099,POINT (-118.79910 34.14448)
84,LA County,LA County Library - Willowbrook Library,Los Angeles,90059,33.925432,-118.238994,POINT (-118.23899 33.92543)
85,LA County,LA County Library - Wiseburn Library,Hawthorne,90250,33.909533,-118.373157,POINT (-118.37316 33.90953)
86,LA County,LA County Library - Woodcrest Library,Los Angeles,90044,33.939857,-118.299580,POINT (-118.29958 33.93986)

Manually identify libaries in South Central LA

In [13]:
south_central_libs = pd.DataFrame()
south_central_libs = geolibs.loc[lambda df: df['zip'] == 90037]
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90001])
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90007])
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90255])
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90059])
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90061])
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90062])
south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90280])

south_central_libs

/tmp/ipykernel_204/3682315964.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90001])
/tmp/ipykernel_204/3682315964.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90007])
/tmp/ipykernel_204/3682315964.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90255])
/tmp/ipykernel_204/3682315964.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90059])
/tmp/ipykernel_204/3682315964.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90061])
/tmp/ipykernel_204/3682315964.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90062])
/tmp/ipykernel_204/3682315964.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  south_central_libs = south_central_libs.append(geolibs.loc[lambda df: df['zip'] == 90280])

,org_name,Name,city,zip,latitude,longitude,geometry
96,City of LA,Los Angeles Public Library - Vermont Square Br...,Los Angeles,90037,33.999722,-118.295962,POINT (-118.29596 33.99972)
139,City of LA,Los Angeles Public Library - Junipero Serra Br...,Los Angeles,90037,34.001674,-118.274192,POINT (-118.27419 34.00167)
28,LA County,LA County Library - Florence Express Library,Los Angeles,90001,33.974532,-118.245088,POINT (-118.24509 33.97453)
31,LA County,LA County Library - Graham Library,Los Angeles,90001,33.959945,-118.238352,POINT (-118.23835 33.95994)
37,LA County,LA County Library - Huntington Park Library,Huntington Park,90255,33.980349,-118.218687,POINT (-118.21869 33.98035)
84,LA County,LA County Library - Willowbrook Library,Los Angeles,90059,33.925432,-118.238994,POINT (-118.23899 33.92543)
0,LA County,LA County Library - A C Bilbrew Library,Los Angeles,90061,33.916229,-118.272075,POINT (-118.27207 33.91623)
112,City of LA,Los Angeles Public Library - Exposition Park B...,Los Angeles,90062,34.014461,-118.308716,POINT (-118.30872 34.01446)
36,LA County,LA County Library - Hollydale Library,South Gate,90280,33.917716,-118.168596,POINT (-118.16860 33.91772)
46,LA County,LA County Library - Leland R. Weaver Library,South Gate,90280,33.944098,-118.201418,POINT (-118.20142 33.94410)

Write a function to caluclate the haversine distance between to lat-lon points. Found this on GIS StackExchange.

In [14]:
from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 3956 # Radius of earth in miles. Use 6371 for kilometers
    return c * r

Let's select the Junipero Serra Branch Library as the location nearest to the Historic South Central neighborhood.

In [15]:
lon1 = -118.274350
lat1 = 34.001730

# New list for distances
haversine_distances = []

for i,j in south_central_centroids.iterrows():
    coord = j
    lon2 = coord['lon']
    lat2 = coord['lat']
    haversine_var = haversine(lon1, lat1, lon2, lat2)
    haversine_distances.append(haversine_var)
    
print("List of distances from each tract centroid to the Junipero Serra Branch Library:")
print()
print(haversine_distances)

List of distances from each tract centroid to the Junipero Serra Branch Library:

[2.012019732477354, 0.881818564061368, 1.6982521722857413, 1.704943108898838, 2.0894602015637056, 1.9478905812776395, 1.607047057790319, 1.3359445655150102, 0.952540252591208, 0.4724215601215651, 1.3359445655150102]

Now write a function that finds the average value of a list. Use it to calculate the average distance from census tract centroids to the nearest library.

In [17]:
def average(lst):
    return sum(lst) / len(lst)
avg_dist_to_library = average(haversine_distances) 
print("average distance to nearest public library", avg_dist_to_library, "miles")

average distance to nearest public library 1.4580256692816143 miles